name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up node_modules cache
      uses: actions/cache@v2
      id: node-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Install node packages
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Run lint
      run: yarn lint-check
